### ISSUE TITLE
Transformations on attributes

### ISSUE THREAD

**Issue by jackturnbull** [imdrasil/form_object#2]
Thanks for the library (and the nice abstraction)!

I'm hoping to use this for the following example model and form:

```crystal
# models/user.cr
class User < Jennifer::Model::Base
  mapping(
    id: {type: String, primary: true},
    email: String,
    encrypted_password: String
  )
end
```
```crystal
# forms/user.cr
class UserForm < FormObject::Base(User)
  attr :email, String
  attr :password, String, virtual: true
end
```

But what I want to do is encrypt the password after validation, e.g something like the below:

```crystal
# forms/user.cr
class UserForm < FormObject::Base(User)
  attr :email, String
  attr :password, String, origin: :encrypted_password, transformer: :encrypted_password

  def encrypted_password(value : String)
    Crypto::Bcrypt::Password.new(value)
  end
end
```

Or even:

```crystal
# forms/user.cr
class UserForm < FormObject::Base(User)
  attr :email, String
  attr :password, String, origin: :encrypted_password, after_validate: :transform_password

  def transform_password(value : String)
    Crypto::Bcrypt::Password.new(value)
  end
end
```

What do you think the best way of handling this is, as it currently stands? I have a couple of ideas:
* Create a persist method to extend/overload the save method (or overload the save method itself)
  * **+** Simple
  * **-** If I need to do multiple fields it could end up becoming bloated
* Overload the setter created by the macro
  * **+** Runs on a per-attr basis, cleaner
  * **-** Likely won't work as the field isn't stored in the MAPPING

**Comment by imdrasil** [comment]
As you are using this lib with Jennifer the case with encrypting user password can be held as [here](https://github.com/imdrasil/kemal_and_jennifer_sample_app/blob/master/src/form_objects/new_user_form.cr) (this is not the final version but has general vision). In common case it might be useful to have build-in mechanism of additional field transformation, but we need several cases at least to be able to design a good approach.

**Comment by jackturnbull** [comment]
Thanks for the quick response :)

I understand, and wouldn't expect you to build it from a single use-case. I'm happy cloning the approach from the example you linked - I'll get back to you if there's many more examples but I suspect this would be my main use case for now so feel free to close the issue if you prefer.

**Comment by imdrasil** [comment]
Perhaps later I'll think about adding some additional abstraction around sign up form. Feel free to reopen this issue whether you find out more use-cases for this.
