### ISSUE TITLE
Error when trying to run shads command

### ISSUE THREAD

**Issue by matheusburey** [imdrasil/form_object#3]
when trying to run the shads command I got this error following the tutorial

```
Could not find commit 24a43bc89cf58d6d6c945ef236cb80227e853c21 for shard "view_model" in the repository https://github.com/imdrasil/view_model.cr.git
```

**Comment by imdrasil** [comment]
Hi, this project was "a bit" outdated. Temporary you can use master branch instead of a version but take into account that it wasn't tested against latest crystal version
